name: Master Push Trigger
on:
  push:
    branches: [ master ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send Deployment Signal
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: joshua5201/AgentPassVault-Deployment
          event-type: master-push
          client-payload: '{"sha": "${{ github.sha }}"}'
